# 服务端口号
server:
  port: 8080

custom:
  init-sql: classpath:init.sql

spring:
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
  data:
    # Redis 相关配置
    redis:
      host: localhost
      port: 6379
      database: 0
  jackson:
    time-zone: GMT+8
  datasource:
    # MySQL 相关配置
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/e2echo?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: root
    password: root
    hikari:
      # 自动检测连接
      connection-test-query: SELECT 1
      # 数据库连接超时时间,默认30秒
      connection-timeout: 60000
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 500000
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 540000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 12
      # 最小空闲连接数量
      minimum-idle: 10
      # 连接池名称
      pool-name: SPHHikariPool

#用于打印框架生成的sql语句，便于调试
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Minio 配置
minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: e2echo

springdoc:
  # 默认是false，需要设置为true
  default-flat-param-object: true

jwt-utils:
  secret-key: 85a761e3b9464d3f9bdfa36cb65114ed
  expiration-day: 3650
