# 用于打印框架生成的sql语句，便于调试
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

custom:
  init-sql: classpath:schema.sql

spring:
  jackson:
    time-zone: GMT+8
  datasource:
    initialization-mode: always
    # H2 数据库相关配置
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:./mydb
    username: root
    password: root
    hikari:
      # 自动检测连接
      connection-test-query: SELECT 1
      # 数据库连接超时时间,默认30秒
      connection-timeout: 60000
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 500000
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 540000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 12
      # 最小空闲连接数量
      minimum-idle: 10
      # 连接池名称
      pool-name: SPHHikariPool
