server:
  port: 8080

spring:
  application:
    name: e2echo-server

  datasource:
    url: jdbc:postgresql://localhost:5432/e2echo-server
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
